### ISSUE TITLE
[ADD FRONTEND] : Contact Us Page Added

### ISSUE THREAD

**Issue by shuvadeepmondal** [Bug-Bust3rs/UNITE#44]
### Frontend Summary 📝

`/contact`

### Development Approach 🚀

Any query page Added

### Deployment Status

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hello @shuvadeepmondal! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
  If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
  Happy coding!✨ We hope to see you again soon!❣️

**Comment by Puskar-Roy** [comment]
Hello @shuvadeepmondal! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
  If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
  Happy coding!✨ We hope to see you again soon!❣️
